# Generated by Django 5.2.6 on 2025-09-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal User'), ('provider', 'Provider')], db_index=True, default='normal', max_length=20),
        ),
    ]
