# Generated by Django 5.2.6 on 2025-09-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_business_name_userprofile_business_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderServiceType',
            fields=[
                ('slug', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
