# Generated by Django 5.2.6 on 2025-09-24 07:51

import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailchangerequest',
            new_name='users_email_expires_536139_idx',
            old_name='users_email_expire_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='users_users_user_id_fb913d_idx',
            old_name='users_sess_user_id_3c440a_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='users_users_jti_has_385df3_idx',
            old_name='users_sess_jti_has_6c4c69_idx',
        ),
        migrations.AddField(
            model_name='usersession',
            name='public_id',
            field=models.CharField(db_index=True, default=users.models.UserSession._new_public_id, max_length=22, unique=True),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'revoked_at'], name='users_users_user_id_06db0b_idx'),
        ),
    ]
