# Generated by Django 5.2.6 on 2025-09-20 09:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type_label', models.CharField(blank=True, max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('price_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('features', models.JSONField(blank=True, default=list)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
                ('venue_attrs', models.JSONField(blank=True, default=dict, null=True)),
                ('attire_attrs', models.JSONField(blank=True, default=dict, null=True)),
                ('catering_attrs', models.JSONField(blank=True, default=dict, null=True)),
                ('rental_attrs', models.JSONField(blank=True, default=dict, null=True)),
                ('service_attrs', models.JSONField(blank=True, default=dict, null=True)),
                ('accessory_attrs', models.JSONField(blank=True, default=dict, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.category')),
            ],
            options={
                'indexes': [models.Index(fields=['-featured', '-rating'], name='listing_featured_rating_idx'), models.Index(fields=['rating'], name='listing_rating_idx'), models.Index(fields=['price_min'], name='listing_price_min_idx'), models.Index(fields=['category', 'featured'], name='listing_category_featured_idx')],
            },
        ),
    ]
