# Generated by Django 5.2.6 on 2025-09-16 20:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="specialty_attrs",
            new_name="service_attrs",
        ),
        migrations.AddField(
            model_name="listing",
            name="price_min",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
