# Generated by Django 5.2.6 on 2025-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_rename_specialty_attrs_listing_service_attrs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="capacity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
