# Generated by Django 5.2.6 on 2025-09-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_created_by_listing_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
