# Generated by Django 5.2.6 on 2025-09-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
