# Generated by Django 5.2.6 on 2025-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_listing_capacity"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["-featured", "-rating"], name="listing_featured_rating_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["rating"], name="listing_rating_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price_min"], name="listing_price_min_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["category", "featured"], name="listing_category_featured_idx"
            ),
        ),
    ]
