# Generated by Django 5.2.6 on 2025-09-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingavailability'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listingavailability',
            new_name='listings_li_listing_9d4a9d_idx',
            old_name='listings_li_listing_7ff800_idx',
        ),
        migrations.RenameIndex(
            model_name='listingavailability',
            new_name='listings_li_listing_dac3b4_idx',
            old_name='listings_li_listing_c8ab45_idx',
        ),
    ]
