#!/usr/bin/env python
"""Generate a TypeScript types file for provider meta based on backend constants and service types.
For now, this only includes country union and dial code record shape.
"""
from pathlib import Path
import json
from users.constants import ALLOWED_PROVIDER_COUNTRIES, DIAL_CODE_MAP

OUT = Path(__file__).resolve().parents[2] / 'habesha-wedding-dream' / 'src' / 'types' / 'providerMeta.generated.ts'
OUT.parent.mkdir(parents=True, exist_ok=True)

countries_sorted = sorted(ALLOWED_PROVIDER_COUNTRIES)
country_union = ' | '.join([f'"{c}"' for c in countries_sorted])

ts = f"""// AUTO-GENERATED by generate_provider_meta_types.py — DO NOT EDIT MANUALLY
export type ProviderCountry = {country_union};
export interface ProviderMetaPayload {{
  version?: string;
  countries: ProviderCountry[];
  dial_codes: Record<ProviderCountry, string>;
  service_types: Array<{{ slug: string; name: string }}>;
}}
"""
OUT.write_text(ts, encoding='utf-8')
print(f"Wrote {OUT}")
